using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;
using System;
using System.IO;
using System.Collections.Generic;
using System.Security.Cryptography;
using System.Linq;
using System.Text;
using System.Runtime;
using Ionic.Zip;
using Ionic.Zlib;
using MSBuild.XCode.Helpers;

namespace MSBuild.XCode
{
    public class PackageCreate : Task
    {
        public string Path { get; set; }
        public string Name { get; set; }
        public string ZipFilename { get; set; }

        public override bool Execute()
        {
            bool success = false;

            if (!Path.EndsWith("\\"))
                Path = Path + "\\";

            /// 1) Create zip file
            /// 2) For every file create an MD5 and gather them into a sfv file
            /// 3) Remove root from every source file
            /// 4) Set the work directory
            /// 5) Add files to zip
            /// 6) Close
            /// 
            DirectoryScanner scanner = new DirectoryScanner(new xDirname(Path + "\\" + Name));
            scanner.scanSubDirs = true;
            scanner.collect(new xDirname(""), "*.*", DirectoryScanner.EmptyFilterDelegate);

            Environment.CurrentDirectory = Path + "\\" + Name;

            MD5CryptoServiceProvider md5_provider = new MD5CryptoServiceProvider();
            Dictionary<string, byte[]> crcDict = new Dictionary<string, byte[]>();
            List<KeyValuePair<string, string>> sourceFilenames = new List<KeyValuePair<string, string>>();
            foreach (xFilename filename in scanner.filenames)
            {
                string src_filename = Name + "\\" + filename;

                FileStream fs = new FileStream(Path + "\\" + src_filename, FileMode.Open, FileAccess.Read);
                byte[] md5 = md5_provider.ComputeHash(fs);
                fs.Close();
                crcDict.Add(src_filename, md5);

                string zip_filename = src_filename;
                sourceFilenames.Add(new KeyValuePair<string, string>(src_filename, System.IO.Path.GetDirectoryName(src_filename)));
            }

            Environment.CurrentDirectory = Path;

            string sfv_filename = Name + ".md5";
            using (FileStream wfs = new FileStream(sfv_filename, FileMode.Create))
            { 
                StreamWriter writer = new StreamWriter(wfs);
                writer.WriteLine("; generated by msbuild.xmaven");
                foreach (KeyValuePair<string, byte[]> k in crcDict)
                {
                    writer.WriteLine("{0} *{1}", k.Key, StringTools.MD5ToString(k.Value));
                }
                writer.Close();
                wfs.Close();

                sourceFilenames.Add(new KeyValuePair<string, string>(sfv_filename, ""));
            }

            if (File.Exists(ZipFilename))
            {
                try { File.Delete(ZipFilename); }
                catch(Exception) {}
            }

            using (ZipFile zip = new ZipFile(ZipFilename))
            {
                foreach (KeyValuePair<string, string> p in sourceFilenames)
                    zip.AddFile(Path + "\\" + p.Key, p.Value);

                zip.Save();
                success = true;
            }
            return success;
        }
    }
}
